namespace OsuPlayer
{
    runtimeclass GroupedData : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        GroupedData();
        String Title{ get; set; };
        Windows.Foundation.Collections.IObservableVector<String> data{ get; set; };
        void Raise();
    }

    [default_interface]
    runtimeclass ArtistView : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ArtistView();
        
        /*Resource */
        Windows.UI.Xaml.Data.CollectionViewSource AlphabetGroups{ get; };

        Windows.Foundation.Collections.IObservableVector<GroupedData> groups{ get; };
        
    }
}
