import "ViewModel.CollectionItem.idl";
namespace OsuPlayer
{
    [default_interface]
    runtimeclass CollectionView : Windows.UI.Xaml.Controls.Page
    {
        CollectionView();

        Windows.Foundation.Collections.IObservableVector<OsuPlayer.ViewModel.CollectionItem> Collections{ get; };
    }
}
