import "CollectionItemViewModel.idl";
namespace OsuPlayer
{
    [default_interface]
    runtimeclass CollectionView : Windows.UI.Xaml.Controls.Page
    {
        CollectionView();

        //Windows.UI.Xaml.Data.CollectionViewSource CollectionsCVS{ get; };
        Windows.Foundation.Collections.IObservableVector<CollectionItemViewModel> CollectionItems{ get; };
    }
}
