import "ViewModel.MyMusic.idl";
namespace OsuPlayer
{
    [default_interface]
    runtimeclass CollectionView : Windows.UI.Xaml.Controls.Page
    {
        CollectionView();

        OsuPlayer.ViewModel.MyMusicViewModel ViewModel{ get; };
    }
}
