import "SongItem.idl";

namespace OsuPlayer
{
    [bindable]
    [default_interface]
    runtimeclass CollectionItemViewModel 
    {
        CollectionItemViewModel();
        
        String Name{ get; set; };
        Windows.Foundation.Collections.IObservableVector<SongItem> SongItems{ get; };

        Int32 Count{ get; };
    }
}
