import "Player.idl";
import "ViewModel.MyMusic.idl";
namespace OsuPlayer
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();

        Player player{ get; };
        OsuPlayer.ViewModel.MyMusicViewModel MyMusicViewModel{ get; };
        static Microsoft.UI.Xaml.Controls.WebView2 Browser{get;};
    }
}
