import "ViewModel.MyMusic.idl";
namespace OsuPlayer
{
    [default_interface]
    runtimeclass MyMusic : Windows.UI.Xaml.Controls.Page
    {
        MyMusic();

        //void OnSongItemEvent(Windows.Storage.StorageFile file);
        void OnSongItemEvent(OsuPlayer.ViewModel.SongItemViewModel item);

        OsuPlayer.ViewModel.MyMusicViewModel ViewModel{ get; };

        //Windows.UI.Xaml.Controls.ComboBoxItem SortOrderSelection{ get; };
    }
}
