import "ViewModel.MyMusic.idl";
namespace OsuPlayer
{
    [default_interface]
    runtimeclass MyMusic : Windows.UI.Xaml.Controls.Page
    {
        MyMusic();

        //void OnSongItemEvent(Windows.Storage.StorageFile file);
        void OnSongItemEvent(OsuPlayer.ViewModel.SongItemViewModel item);

        Windows.UI.Xaml.Controls.ListView MusicList{ get; };
        OsuPlayer.ViewModel.MyMusicViewModel ViewModel{ get; };
    }
}
