import "SongItem.idl";
namespace OsuPlayer
{
    [bindable]
    [default_interface]
    runtimeclass MyMusicViewModel 
    {
        MyMusicViewModel();
        
        Int32 SortByIndex{ get; set; };

        Windows.Foundation.Collections.IObservableVector<SongItem> Songs{ get; };
    }
}
