import "ViewModel.OsuPathItem.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass OsuPathItem : Windows.UI.Xaml.Controls.UserControl
    {
        OsuPathItem();
        
        //Construct directly with a view model
        OsuPathItem(OsuPlayer.ViewModel.OsuPathItemViewModel viewModel);
        
        //The view-model
        OsuPlayer.ViewModel.OsuPathItemViewModel ViewModel{ get; };
    }
}
