namespace OsuPlayer
{
    [bindable]
    [default_interface]
    runtimeclass OsuPathItemViewModel 
    {
        OsuPathItemViewModel();
        
        Boolean IsLoading{ get; set; };
        String Path{ get; set; };
        Int32 BeatmapCount{ get; set; };
    }
}
