import "OsuPathItemViewModel.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass OsuPathItem : Windows.UI.Xaml.Controls.UserControl
    {
        OsuPathItem();
        
        //The view-model
        OsuPathItemViewModel ViewModel{ get; };
    }
}
