import "PlayerViewModel.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass Player : Windows.UI.Xaml.Controls.UserControl
    {
        Player();
        
        //The view-model
        PlayerViewModel ViewModel{ get; };
    }
}
