import "SongItem.idl";


namespace OsuPlayer
{
    enum PlayMod
    {
        Normal,
        HalfTime,
        DoubleTime,
        NightCore
    };


    [bindable]
    [default_interface]
    runtimeclass PlayerViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        PlayerViewModel();

        void Play(SongItem item);
        void Play();
        void PlayPrevious();
        void PlayNext();
        
        PlayMod Mod{ get; set; };
        Boolean UseSkinHitsound{ get; set; };
        Int32 Volume{ get; set; };
        Windows.UI.Xaml.Media.ImageSource ImageSource{ get; };

        String ProgressString{ get; };
        String SongLengthString{ get; };

        Int32 SongLength{ get; };
        Int32 Progress{ get; };
    }
}
