import "ViewModel.Player.idl";
import "ViewModel.Settings.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass Player : Windows.UI.Xaml.Controls.UserControl
    {
        Player();
        
        Windows.UI.Xaml.Controls.Slider VolumeSlider{ get; };
        Windows.UI.Xaml.Controls.Slider SongVolumeSlider{ get; };
        Windows.UI.Xaml.Controls.Slider HitsoundVolumeSlider{ get; };
        //The view-model
        OsuPlayer.ViewModel.PlayerViewModel ViewModel{ get; };
        OsuPlayer.ViewModel.SettingsViewModel SettingsViewModel{ get; };
    }
}
