import "SongItem.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass Player : Windows.UI.Xaml.Controls.UserControl
    {
        Player();

        void Play(SongItem item);
        //void Play2(Windows.Storage.StorageFile song);
        
        Windows.UI.Xaml.Media.ImageSource ImageSource{ get; };
    }
}
