namespace OsuPlayer
{
    [bindable]
    [default_interface]
    runtimeclass ReferenceToVisibilityConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        ReferenceToVisibilityConverter();
    }
}
