import "SearchPageViewModel.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass SearchPage : Windows.UI.Xaml.Controls.Page
    {
        SearchPage();

        //The view-model
        SearchPageViewModel ViewModel{ get; };
    }
}
