import "ViewModel.SongProperty.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass SongItemDialog : Windows.UI.Xaml.Controls.Page
    {
        SongItemDialog();

        OsuPlayer.ViewModel.SongPropertyViewModel ViewModel{ get; set; };
    }
}
