namespace OsuPlayer
{
    [default_interface]
    runtimeclass SongItemDialog : Windows.UI.Xaml.Controls.Page
    {
        SongItemDialog();

        String Title{ get; set; };
        String Singer{ get; set; };
        String Tags{ get; set; };
        String Bitrate{ get; set; };
        String Length{ get; set; };
        String SongPath{ get; set; };
    }
}
