namespace OsuPlayer
{
    [default_interface]
    runtimeclass SongItem : Windows.UI.Xaml.Controls.UserControl
    {
        SongItem();
        String SongName{ get;};
        String Singer{ get;};
        String Mapper{ get;};
        String Length{ get;};
    }
}
