import "SongItemViewModel.idl";

namespace OsuPlayer
{
    [default_interface]
    runtimeclass SongItem : Windows.UI.Xaml.Controls.UserControl
    {
        SongItem();

        SongItem(SongItemViewModel viewModel);
        
        //The view-model
        SongItemViewModel ViewModel{ get; };
    }
}
