namespace OsuPlayer
{
    [bindable]
    [default_interface]
    runtimeclass SongPropertyViewModel 
    {
        SongPropertyViewModel();


        String Title{ get; set; };
        String Tags{ get; set; };
        String Bitrate{ get; set; };
        String Length{ get; set; };
        String SongPath{ get; set; };
    }
}
