import "ViewModel.SongItem.idl";

namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass CollectionItem
    {
        CollectionItem();
        
        String Name{ get; };
        Windows.Foundation.Collections.IObservableVector<OsuPlayer.ViewModel.SongItemViewModel> SongItems{ get; };
        IInspectable ModelPointer{ get; set; };

        Int32 Count{ get; };
    }
}
