namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass SongItemViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SongItemViewModel();


        String SongName{ get; };
        String Singer{ get; };
        String Mapper{ get; };
        Int32 Length{ get; };
        String LengthString{ get; };

        IInspectable ModelPointer{ get; set; };
        Windows.Storage.StorageFolder Folder{ get; };

        Windows.Foundation.Collections.IObservableVector<String> Versions{ get; };

        Int32 SelectedVersionIndex{ get; set; };
        String SelectedVersion{ get; };
        Boolean IsPlaying{ get; set; };
        event Windows.Foundation.EventHandler<Boolean> IsPlayingChanged;

        Windows.Foundation.IAsyncAction ShowProperty();
        Windows.Foundation.IAsyncAction OpenFile();
        Windows.Foundation.IAsyncAction OpenFolder();

        void PlayCurrent();

        //For binding in xaml
        Windows.UI.Xaml.Media.Imaging.BitmapImage SongImage{ get; };
        Windows.Foundation.IAsyncOperation<Windows.Storage.StorageFile> SongImageFile{ get; };
        Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IRandomAccessStream> SongImageStream{ get; };
        Windows.Foundation.IAsyncAction loadImage();
    }
}
