namespace OsuPlayer.ViewModel
{
    runtimeclass HitsoundSample : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        HitsoundSample(String name);
        String Name{ get; };
        Int32 Volume{ get; set; };
        Boolean IsAvailable{ get; };

        void Play();
        void Save(); //Save settings
        Windows.Foundation.IAsyncAction Update();
    };

    runtimeclass HitsoundSampleSet
    {
        HitsoundSampleSet(String sampleSetName);
        HitsoundSample Hitnormal{ get; };
        HitsoundSample Hitfinish{ get; };
        HitsoundSample Hitwhistle{ get; };
        HitsoundSample Hitclap{ get; };
    };

    [bindable]
    [default_interface]
    runtimeclass HitsoundPanelViewModel
    {
        HitsoundPanelViewModel();

        HitsoundSampleSet Normal{ get; };
        HitsoundSampleSet Soft{ get; };
        HitsoundSampleSet Drum{ get; };

        Windows.Foundation.IAsyncAction Update();
    }
}
