import "ViewModel.SongItem.idl";
import "ViewModel.CollectionItem.idl";
namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass MyMusicViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        MyMusicViewModel();

        String ListName{ get; set; };
        
        Int32 SortByIndex{ get; set; };

        Windows.Foundation.Collections.IObservableVector<OsuPlayer.ViewModel.SongItemViewModel> Songs{ get; set; };
        Windows.Foundation.IAsyncAction PlayCollection();
        //Windows.Foundation.Collections.IObservableVector<OsuPlayer.ViewModel.CollectionItem> Collections{ get; };
    }
}
