import "ViewModel.SongItem.idl";
namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass MyMusicViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        MyMusicViewModel();
        
        Int32 SortByIndex{ get; set; };

        Windows.Foundation.IAsyncAction ShowPropertyOf(OsuPlayer.ViewModel.SongItemViewModel songItem);
        Windows.Foundation.Collections.IObservableVector<OsuPlayer.ViewModel.SongItemViewModel> Songs{ get; set; };
    }
}
