namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass SongItemViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SongItemViewModel();


        String SongName{ get; };
        String Singer{ get; };
        String Mapper{ get; };
        Int32 Length{ get; };
        String LengthString{ get; };

        IInspectable ModelPointer{ get; set; };

        Windows.Foundation.Collections.IObservableVector<String> Versions{ get; };

        Int32 SelectedVersionIndex{ get; set; };
        String SelectedVersion{ get; };

        Windows.Foundation.IAsyncAction ShowProperty();

        void PlayCurrent();

        //For binding in xaml
        Windows.UI.Xaml.Media.Imaging.BitmapImage SongImage{ get; };
        Windows.Foundation.IAsyncOperation<Windows.Storage.StorageFile> SongImageFile{ get; };
        Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IRandomAccessStream> SongImageStream{ get; };
        Windows.Foundation.IAsyncAction loadImage();
    }
}
