namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass SongItemViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SongItemViewModel();


        String SongName{ get; set; };
        String Singer{ get; set; };
        String Mapper{ get; set; };
        Int32 Length{ get; set; };
        String LengthString{ get; };

        Int32 Index{ get; set; };

        IInspectable ModelPointer{ get; set; };

        //Windows.Media.Core.MediaSource SongFile{ get; };
        //Windows.UI.Xaml.Media.Imaging.BitmapImage Image{ get; };
        Windows.Foundation.Collections.IObservableVector<String> Versions{ get; };

        Int32 SelectedVersionIndex{ get; set; };

        //Windows.Foundation.IAsyncAction ShowProporty();

        void PlayCurrent();
    }
}
