import "ViewModel.OsuPathItem.idl";
namespace OsuPlayer.ViewModel
{
    enum Mod
    {
        Normal,
        HalfTime,
        DoubleTime,
        NightCore
    };

    enum AddOsuFolderResult
    {
        Success,
        Invalid,
        Duplicate
    };

    [bindable]
    [default_interface]
    runtimeclass SettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsViewModel();
    
        //Methods
        Windows.Foundation.IAsyncOperation<AddOsuFolderResult> AddOsuPath();

        //Data
        Int32 ThemeIndex{ get; set; };
        Boolean IsModEnabled{ get; set; };
        Mod DefaultMod{ get; set; };
        Boolean HitsoundGlobalEnabled{ get; set; };
        Windows.Storage.StorageFolder SelectedSkin{ get; set; };

        Int32 OsuPathActionIndex{ get; set; };
        Int32 LinkActionIndex{ get; set; };
        String CustomSearchPrefix{ get; set; };
        Windows.UI.Xaml.Visibility CustomSearchTextBoxVisibility{ get; };
        Int32 JumpListRecentSongs{ get; set; };
        Int32 JumpListRecentCollections{ get; set; };
        Boolean AllowModifyOsuData{ get; set; };
        Windows.Foundation.Collections.IObservableVector<OsuPlayer.ViewModel.OsuPathItemViewModel> OsuPaths{ get; };
        
        //Windows.Storage.StorageFolder SelectedSkin{ get; set; };
        String ExperimentSettingHeaderText{ get; };
    }
}
