import "ViewModel.SongItem.idl";
namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass SearchPageViewModel 
    {
        SearchPageViewModel();
        
        String Keyword{ get; set; };
        String SearchInfo{ get; };
        Windows.Foundation.Collections.IObservableVector<OsuPlayer.ViewModel.SongItemViewModel> SearchResult{ get; };
    }
}
