import "OsuPathItem.idl";

namespace OsuPlayer.ViewModel
{
    enum Mod
    {
        Normal,
        HalfTime,
        DoubleTime,
        NightCore
    };

    enum AddOsuFolderResult
    {
        Success,
        Invalid,
        Duplicate
    };

    [bindable]
    [default_interface]
    runtimeclass SettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsViewModel();
    
        //Methods
        Windows.Foundation.IAsyncOperation<AddOsuFolderResult> AddOsuPath();

        //Data
        Int32 ThemeIndex{ get; set; };
        Boolean IsModEnabled{ get; set; };
        Mod DefaultMod{ get; set; };

        Int32 JumpListRecentSongs{ get; set; };
        Int32 JumpListRecentCollections{ get; set; };
        Boolean AllowModifyOsuData{ get; set; };
        Windows.Foundation.Collections.IObservableVector<OsuPlayer.OsuPathItem> OsuPaths{ get; };
        Windows.Foundation.Collections.IObservableVector<String> Skins{ get; };
    }
}
