import "OsuPathItem.idl";

namespace OsuPlayer.ViewModel
{
    enum Mod
    {
        Normal,
        HalfTime,
        DoubleTime,
        NightCore
    };

    [bindable]
    [default_interface]
    runtimeclass SettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsViewModel();
    
        //Methods
        Windows.Foundation.IAsyncAction AddOsuPath();
        void ClearAll();

        //Data
        Mod DefaultMod{ get; set; };
        Windows.Foundation.Collections.IObservableVector<OsuPlayer.OsuPathItem> OsuPaths{ get; };
        Windows.Foundation.Collections.IObservableVector<String> Skins{ get; };
    }
}
