import "ViewModel.SongItem.idl";
import "ViewModel.CollectionItem.idl";

namespace OsuPlayer.ViewModel
{
    [bindable]
    [default_interface]
    runtimeclass RecentViewModel 
    {
        RecentViewModel();

        Windows.Foundation.Collections.IObservableVector<Object> RecentItems{get;};

        void addSongRecord(OsuPlayer.ViewModel.SongItemViewModel songItem);
        void addCollectionRecord(OsuPlayer.ViewModel.CollectionItem songItem);
    }
}
