import "ViewModel.SongItem.idl";

namespace OsuPlayer.ViewModel
{
    enum PlayMod
    {
        Normal,
        HalfTime,
        DoubleTime,
        NightCore
    };


    [bindable]
    [default_interface]
    runtimeclass PlayerViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        PlayerViewModel();

        Windows.Foundation.IAsyncAction Play(OsuPlayer.ViewModel.SongItemViewModel item);
        Windows.Foundation.IAsyncAction PlayList(Windows.Media.Playback.MediaPlaybackList list);

        //Control buttons
        void PlayCurrent();
        void PlayPrevious();
        void PlayNext();

        void Mute();


        //Volumes
        Int32 Volume{ get; set; };
        Int32 SongVolume{ get; set; };
        Int32 HitsoundVolume{ get; set; };
        void Save();
        
        //Playing info
        PlayMod Mod{ get; set; };
        Boolean IsModEnabled{ get; set; };
        String ModString{ get; };
        Boolean UseSkinHitsound{ get; set; };
        Boolean HasItems{ get; };

        Windows.UI.Xaml.Media.ImageSource ImageSource{ get; };


        Int32 SongLength{ get; };
        Int32 Progress{ get; };
    }
}
